spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/e_db
    username: postgres
    password: your_local_password
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update   # use 'update' locally
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

payment:
  gateway:
    simulate-failure-rate: 0.05   # 5% failure simulation

logging:
  level:
    com.distrishop: DEBUG